#!/bin/sh
g++ -o wipeout-port \
    -I. -g -O0 -fsanitize=address -fno-omit-frame-pointer \
    -Wno-array-bounds \
    -Wno-c++11-compat-deprecated-writable-strings \
    -Wno-constant-conversion \
    -Wno-empty-body \
    -Wno-extern-initializer \
    -Wno-format-security \
    -Wno-parentheses-equality \
    -Wno-tautological-constant-out-of-range-compare \
    -Wno-tautological-pointer-compare \
    -DWIPEOUTPC \
    -include stdint.h \
    wipesrc/wipeout98/small_ptr.cpp \
    wipesrc/wipeout98/ajs.cpp \
    wipesrc/wipeout98/andyscn.cpp \
    wipesrc/wipeout98/ayrace.cpp \
    wipesrc/wipeout98/camera.cpp \
    wipesrc/wipeout98/card.cpp \
    wipesrc/wipeout98/clearot.cpp \
    wipesrc/wipeout98/collide.cpp \
    wipesrc/wipeout98/cone.cpp \
    wipesrc/wipeout98/config.cpp \
    wipesrc/wipeout98/control.cpp \
    wipesrc/wipeout98/credits.cpp \
    wipesrc/wipeout98/datacash.cpp \
    wipesrc/wipeout98/draw.cpp \
    wipesrc/wipeout98/drawot.cpp \
    wipesrc/wipeout98/droid.cpp \
    wipesrc/wipeout98/dynam.cpp \
    wipesrc/wipeout98/effects.cpp \
    wipesrc/wipeout98/error.cpp \
    wipesrc/wipeout98/etcvars.cpp \
    wipesrc/wipeout98/file.cpp \
    wipesrc/wipeout98/fromasm.cpp \
    wipesrc/wipeout98/global.cpp \
    wipesrc/wipeout98/hiscores.cpp \
    wipesrc/wipeout98/hud.cpp \
    wipesrc/wipeout98/init.cpp \
    wipesrc/wipeout98/initpad.cpp \
    wipesrc/wipeout98/libgte.cpp \
    wipesrc/wipeout98/loadall.cpp \
    wipesrc/wipeout98/lzss.cpp \
    wipesrc/wipeout98/main.cpp \
    wipesrc/wipeout98/malloc.cpp \
    wipesrc/wipeout98/menus.cpp \
    wipesrc/wipeout98/newgraphics_stub.cpp \
    wipesrc/wipeout98/object.cpp \
    wipesrc/wipeout98/options.cpp \
    wipesrc/wipeout98/pad.cpp \
    wipesrc/wipeout98/pallette.cpp \
    wipesrc/wipeout98/pdenv.cpp \
    wipesrc/wipeout98/racectrl.cpp \
    wipesrc/wipeout98/radscn.cpp \
    wipesrc/wipeout98/regread_stub.cpp \
    wipesrc/wipeout98/scene.cpp \
    wipesrc/wipeout98/search.cpp \
    wipesrc/wipeout98/ships.cpp \
    wipesrc/wipeout98/skeleton.cpp \
    wipesrc/wipeout98/sound.cpp \
    wipesrc/wipeout98/spline.cpp \
    wipesrc/wipeout98/startpad.cpp \
    wipesrc/wipeout98/tim.cpp \
    wipesrc/wipeout98/timc.cpp \
    wipesrc/wipeout98/track.cpp \
    wipesrc/wipeout98/trackasm.cpp \
    wipesrc/wipeout98/ttf.cpp \
    wipesrc/wipeout98/utils.cpp \
    wipesrc/wipeout98/weapon.cpp \
    wipesrc/wipeout98/win_stub.cpp \
    wipesrc/wipeout98/wincd_stub.cpp \
    wipesrc/wipeout98/winsnd_stub.cpp \
    wipesrc/wipeout98/wintime_stub.cpp
