copy standard.h \wipesrc\wipeout98
copy malloc.h \wipesrc\wipeout98
copy tim.h \wipesrc\wipeout98
copy object.h \wipesrc\wipeout98
copy skeleton.h \wipesrc\wipeout98
copy track.h \wipesrc\wipeout98
copy ships.h \wipesrc\wipeout98
copy weapon.h \wipesrc\wipeout98
copy control.h \wipesrc\wipeout98
copy droid.h \wipesrc\wipeout98
copy camera.h \wipesrc\wipeout98
copy scene.h \wipesrc\wipeout98
copy sound.h \wipesrc\wipeout98
copy sparks2.h \wipesrc\wipeout98
copy global.h \wipesrc\wipeout98
copy combat.h \wipesrc\wipeout98
