void	SetPolyGT3(POLY_GT3 *p);
void	InitAJSVSync(void);
void setWinLose(void);
void	AddPrim(P_TAG *ordt, int32_t depth, uint32_t *p);
void SetSemiTrans(P_TAG *p, int32_t abe);
void SetShadeTex(P_TAG *p, int32_t tge);
void	LoadPilotIntoVram(char *filename);
void LoadClut4(RECT	*rect, uint16_t *clutptr, CLUT *cluts);
int32_t		LoadImage4(RECT	*recp, uint32_t *p, CLUT *cluts);
void LoadClut8(RECT	*rect, uint16_t *clutptr, CLUT *cluts);
int32_t		LoadImage8(RECT	*recp, uint32_t *p, CLUT *cluts);
