ren Ajs.c Ajs.cpp
ren Andyscn.c Andyscn.cpp
ren Ayrace.c Ayrace.cpp
ren CAMERA.C CAMERA.Cpp
ren Card.c Card.cpp
ren Clearot.c Clearot.cpp
ren Collide.c Collide.cpp
ren Combat.c Combat.cpp
ren CONE.C CONE.Cpp
ren Config.c Config.cpp
ren Control.c Control.cpp
ren CRACK.C CRACK.Cpp
ren Credits.c Credits.cpp
ren Datacash.c Datacash.cpp
ren DPA.C DPA.Cpp
ren Draw.c Draw.cpp
ren Drawot.c Drawot.cpp
ren Droid.c Droid.cpp
ren Dynam.c Dynam.cpp
ren EDITOR.C EDITOR.Cpp
ren Effects.c Effects.cpp
ren Error.c Error.cpp
ren Etcvars.c Etcvars.cpp
ren File.c File.cpp
ren fromasm.c fromasm.cpp
ren Getvram.c Getvram.cpp
ren GLOBAL.C GLOBAL.Cpp
ren Grabber.c Grabber.cpp
ren HANDLERS.C HANDLERS.Cpp
ren HISCORES.C HISCORES.Cpp
ren HUD.C HUD.Cpp
ren INIT.C INIT.Cpp
ren Init3d.c Init3d.cpp
ren Initpad.c Initpad.cpp
ren Libgte.c Libgte.cpp
ren Libsnd.c Libsnd.cpp
ren Loadall.c Loadall.cpp
ren LZSS.C LZSS.Cpp
ren Main.c Main.cpp
ren Malloc.c Malloc.cpp
ren Menus.c Menus.cpp
ren Object.c Object.cpp
ren OPTIONS.C OPTIONS.Cpp
ren Pad.c Pad.cpp
ren Pallette.c Pallette.cpp
ren Pdenv.c Pdenv.cpp
ren Pmkey.c Pmkey.cpp
ren Racectrl.c Racectrl.cpp
ren Radscn.c Radscn.cpp
ren RADTRK.C RADTRK.Cpp
ren regread.c regread.cpp
ren SCENE.C SCENE.Cpp
ren SEARCH.C SEARCH.Cpp
ren SHIPS.C SHIPS.Cpp
ren SKELETON.C SKELETON.Cpp
ren Sound.c Sound.cpp
ren Spline.c Spline.cpp
ren Startpad.c Startpad.cpp
ren Stoppad.c Stoppad.cpp
ren TEXPLACE.C TEXPLACE.Cpp
ren TIM.C TIM.Cpp
ren Timc.c Timc.cpp
ren TRACK.C TRACK.Cpp
ren trackasm.c trackasm.cpp
ren Trakview.c Trakview.cpp
ren TTF.C TTF.Cpp
ren UTILS.C UTILS.Cpp
ren VSYNC.C VSYNC.Cpp
ren Wave.c Wave.cpp
ren Weapon.c Weapon.cpp
ren Win.c Win.cpp
ren Wincd.c Wincd.cpp
ren Winclip.c Winclip.cpp
ren Winsnd.c Winsnd.cpp
ren Wintime.c Wintime.cpp
ren WTL.C WTL.Cpp
