//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sjr.rc
//
#ifndef RESOURCE_H
#define RESOURCE_H

#define IDC_DIRECTIONS3 101
#define IDC_INSTALLMOVIES 102
#define IDC_INSTALLDATA 103
#define IDC_DISKSPACE 104
#define IDC_DISKREQUIRED 105
#define IDC_DATASIZE 106
#define IDC_MOVIESSIZE 107
#define IDC_INSTALL 108
#define IDC_DIRECTXDIRECTIONS 109
#define IDC_INSTALLDIRECTX 110
#define IDC_DIRECTXDIRECTIONS2 111
#define IDC_DISKSPACENUMBER 112
#define IDC_DISKREQUIREDNUMBER 113
#define IDC_INSTALLING 114
#define IDC_INSTALLACTION 115
#define IDC_DELETING 116
#define IDC_ACTION 117

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC 1
#define _APS_NEXT_RESOURCE_VALUE 104
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1015
#define _APS_NEXT_SYMED_VALUE 118
#endif
#endif

#endif
