void RotTransPersN(SVECTOR *v0,DVECTOR *v1,u_short *sz,u_short *flag,long n);
long NormalClip( DVECTOR sxy0, DVECTOR sxy1, DVECTOR sxy2 );
long rcos(long a);
long rsin(long a);
long ratan2(long y, long x);
long SquareRoot0( long a );
void SetDrawDistance(long Dist);
void RotTrans( SVECTOR * v0, VECTOR * v1, long * flag );
long RotTransPers(SVECTOR *v0, DVECTOR *sxy, long *p, long *flag);
void CreateSineTable(void);
void SetGeomOffset( long ofx, long ofy);
void SetGeomScreen( long h );
void SetTransMatrix( MATRIX * m );
void SetRotMatrix( MATRIX * m );
MATRIX * MulMatrix0( MATRIX * m0, MATRIX * m1, MATRIX * m2 );
void SetBackColor( long rbk, long gbk, long bbk );
void SetColorMatrix( MATRIX * m );
void SetLightMatrix( MATRIX * m );
MATRIX * TransMatrix( MATRIX * m, VECTOR * v );
void NormalColorCol( SVECTOR * v0, CVECTOR * v1, CVECTOR * v2 );
