int JJSLoadSprites (void);
int randy(void);
void centreMouse(void);
void changeScreen(void);
int	     LockBackBuffer(void);
void	    UnlockBackBuffer(void);
void setRenderBegin(void);
void setRenderEnd(void);
int	     ProcessMessages(void);
void SetContext(void);
void sendList(void);
void	    JJSDrawPolyF3(POLY_F4 * p);
void	    JJSDrawPolyFT3(POLY_FT3 * p);
void	    JJSDrawPolyG3(POLY_G3 * p);
void	    JJSDrawPolyGT3(POLY_GT3 * p);
void	    JJSDrawPolyGT4(POLY_GT4 * p);
void	    JJSDrawPolyF4(POLY_F4 * p);
void	    JJSDrawPolyFT4(POLY_FT4 * p);
void	    JJSDrawPolyG4(POLY_G4 * p);
void	    CopyPal(char *palette, short start, short end);
void	    WinQuit(void);
int JJSJoyConfig(void);
void	    BltClearToScreen(void);
